# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160517_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
