# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20160517_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerID',
            field=models.CharField(default='wew', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='adminID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='userID',
            field=models.CharField(max_length=10),
        ),
    ]
