# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:38
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160515_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='fields',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
